cytometer = 'FACS Canto II'
populations = {}# задать названия нужных для анализа столбцов и желаемое название в отчете
populations['singlets'] = 'Lymph'
populations['T'] = 'T-lymph'
populations['CTL'] = 'CTL'
populations['Ki67+CTL'] = 'Ki67+CTL'
populations['CD69+CTL'] = 'CD69+CTL'
populations['Th'] = 'Th'
populations['Ki67+Th'] = 'Ki67+Th'
populations['CD69+Th'] = 'CD69+Th'
populations['NK'] = 'NK'
populations['Ki67+NK'] = 'Ki67+NK'
populations['CD69+NK'] = 'CD69+NK'
populations['CD56hiNK'] = 'CD56hiNK'
populations['Ki67+CD56hiNK'] = 'Ki67+CD56hiNK'
populations['CD69+CD56hiNK'] = 'CD69+CD56hiNK'
testcv = {}  # cv
testcv['T-lymph'] = ['Lymph', 'no more than', 20]
testcv['Th'] = ['T-lymph', 'no more than', 20]
testcv['CTL'] = ['T-lymph', 'no more than', 20]
testcv['NK'] = ['Lymph', 'no more than', 20]
testcv['CD56hiNK'] = ['NK', 'no more than', 35]
testcv['Ki67+Th'] = ['Th', 'no more than', 35]
testcv['Ki67+Th'] = ['CTL', 'no more than', 35]
testcv['Ki67+NK'] = ['NK', 'no more than', 35]
testcv['Ki67+CD56hiNK'] = ['CD56hiNK', 'no more than', 35]
testcv['CD69+Th'] = ['Th', 'no more than', 35]
testcv['CD69+Th'] = ['CTL', 'no more than', 35]
testcv['CD69+NK'] = ['NK', 'no more than', 35]
testcv['CD69+CD56hiNK'] = ['CD56hiNK', 'no more than', 35] #другое значение
test = {}  # для чего относительно чего считать процент
test['T-lymph'] = 'Lymph'
test['Th'] = 'T-lymph'
test['CTL'] = 'T-lymph'
test['NK'] = 'Lymph'
test['CD56hiNK'] = 'NK'
test['Ki67+Th'] = 'Th'
test['Ki67+Th'] = 'CTL'
test['Ki67+NK'] = 'NK'
test['Ki67+CD56hiNK'] = 'CD56hiNK'
test['CD69+Th'] = 'Th'
test['CD69+Th'] = 'CTL'
test['CD69+NK'] = 'NK'
test['CD69+CD56hiNK'] = 'CD56hiNK'
testmin = {}  # LLOQ, min % child in parent, ставить 0 если нет значения рассчитанного
for i in test:
    if i not in testmin:
        testmin[i] = [test[i], 'not less than', 0]
min_events = {}
min_events['NK'] = 1000
points = 11